Repository khuda-4th/KHUDA-Algorithm-Study, pull requests merged in 2023-11, with the labels that each got.

#31 [121030] Minseo-Jo_1주차 문제 풀이
  Minseo-JO/이코테/Ch7_이진 탐색/부품 찾기.py
Labels: ✨ feat

#38 [231101] mini-min_1주차 문제 풀이
  LeeMinjae/Day 5. 수학, 배열.py
  LeeMinjae/PGS-Coding_Test_Kit/ExhaustiveSearch/42839. 소수 찾기.py
  LeeMinjae/PGS-Coding_Test_Kit/ExhaustiveSearch/42840. 모의고사.py
  LeeMinjae/PGS-Coding_Test_Kit/ExhaustiveSearch/42842. 카펫.py
  LeeMinjae/PGS-Coding_Test_Kit/ExhaustiveSearch/84512. 모음사전.py
  LeeMinjae/PGS-Coding_Test_Kit/ExhaustiveSearch/86491. 최소직사각형.py
  LeeMinjae/PGS-Coding_Test_Kit/ExhaustiveSearch/86971. 전력망을 둘로 나누기.py
  LeeMinjae/PGS-Coding_Test_Kit/ExhaustiveSearch/87946. 피로도.py
  LeeMinjae/PGS-Coding_Test_Kit/Graph/49189. 가장 먼 노드.py
  LeeMinjae/PGS-Coding_Test_Kit/Hash/1845. 폰켓몬.py
  LeeMinjae/PGS-Coding_Test_Kit/Hash/42576. 완주하지 못한 선수.py
  LeeMinjae/PGS-Coding_Test_Kit/Hash/42577. 전화번호 목록.py
  LeeMinjae/PGS-Coding_Test_Kit/Hash/42578. 의상.py
  LeeMinjae/PGS-Coding_Test_Kit/Hash/42579. 베스트앨범.py
  LeeMinjae/PGS-Coding_Test_Kit/Heap/42626. 더 맵게.py
  LeeMinjae/PGS-Coding_Test_Kit/Sorting/42746. 가장 큰 수.py
  LeeMinjae/PGS-Coding_Test_Kit/Sorting/42747. H-index.py
  LeeMinjae/PGS-Coding_Test_Kit/Sorting/42748. K번째수.py
  LeeMinjae/PGS-Coding_Test_Kit/Stack:Queue/12906. 같은 숫자는 싫어.py
  LeeMinjae/PGS-Coding_Test_Kit/Stack:Queue/12909. 올바른 괄호.py
  LeeMinjae/PGS-Coding_Test_Kit/Stack:Queue/42583. 다리를 지나는 트럭.py
  LeeMinjae/PGS-Coding_Test_Kit/Stack:Queue/42584. 주식가격.py
  LeeMinjae/PGS-Coding_Test_Kit/Stack:Queue/42586. 기능개발.py
  LeeMinjae/PGS-Coding_Test_Kit/Stack:Queue/42587. 프로세스.py
Labels: ✨ feat, 📝 docs

#29 [231028] JOONHYUk_Lee_1주차 문제 풀이
  JOONHYUk_LEE/[181914]_9로 나눈 나머지.py
  JOONHYUk_LEE/[181915]_글자 이어붙여 문자열 만들기.py
  JOONHYUk_LEE/[181916]_주사위 게임3.py
  JOONHYUk_LEE/[181917]_간단한 논리연산.py
  JOONHYUk_LEE/[181918]_배열 만들기4.py
  JOONHYUk_LEE/[181919]_콜라츠 수열 만들기.py
  JOONHYUk_LEE/[181920]_카운트업.py
  JOONHYUk_LEE/[181921]_배열 만들기2.py
  JOONHYUk_LEE/[181922]_수열과 구간 쿼리4.py
  JOONHYUk_LEE/[181923]_수열과 구간 쿼리2.py
  JOONHYUk_LEE/[181924]_수열과 구간 쿼리3.py
  JOONHYUk_LEE/[181925]_수 조작하기2.py
  JOONHYUk_LEE/[181926]_수 조작하기1.py
  JOONHYUk_LEE/[181927]_마지막 두 원소.py
  JOONHYUk_LEE/[181928]_이어 붙인 수.py
  JOONHYUk_LEE/[181929]_원소들의 곱과 합.py
  JOONHYUk_LEE/[181930]_주사위 게임2.py
  JOONHYUk_LEE/[181931]_등차수열 특정항 더하기.py
  JOONHYUk_LEE/[181932]_코드 처리.py
  JOONHYUk_LEE/[181933]_flag 따라 다른값 반환.py
  JOONHYUk_LEE/[181934]_조건 문자열.py
  JOONHYUk_LEE/[181935]_홀짝에 따라 다른값 반환.py
  JOONHYUk_LEE/[181936]_공배수.py
  JOONHYUk_LEE/[181937]_n의 배수.py
  JOONHYUk_LEE/[181938]_두 수의 연산값 비교.py
  JOONHYUk_LEE/[181939]_더 크게 합치기.py
  JOONHYUk_LEE/[181940]_문자열 곱하기.py
  JOONHYUk_LEE/[181941]_문자 리스트 문자열 변환.py
  JOONHYUk_LEE/[181942]_문자열 섞기.py
  JOONHYUk_LEE/[181943]_문자열 겹쳐쓰기.py
  JOONHYUk_LEE/[181944]_홀짝 구분하기.py
  JOONHYUk_LEE/[181945]_문자열 돌리기.py
  JOONHYUk_LEE/[181946]_문자열 붙여서 출력.py
  JOONHYUk_LEE/[181947]_덧셈식 출력.py
  JOONHYUk_LEE/[181948]_특수문자 출력.py
  JOONHYUk_LEE/[181949]_대소문자 바꿔서 출력.py
  JOONHYUk_LEE/[181950]_문자열 반복 출력.py
  JOONHYUk_LEE/[181951]_a와 b 출력.py
  JOONHYUk_LEE/[181952]_문자열 출력.py
Labels: ✨ feat

#37 [231031] LimSoYeong_1주차 문제 풀이
  LimSoYeong/PGS/42748 K번째 수(정렬) Level 1.ipynb
  LimSoYeong/PGS/42898 등굣길(DP) Level 3.ipynb
  LimSoYeong/PGS/43105 정수삼각형(DP) Level 3.ipynb
  LimSoYeong/PGS/82612 부족한 금액 계산하기 Level 1.ipynb
  LimSoYeong/PGS/86491_최소직사각형(완전탐색).ipynb
Labels: ✨ feat

#43 🚚 rename: 231102_pull 에러 이슈 관련 파일명 변경
  LeeMinjae/PGS-Coding_Test_Kit/StackQueue/12906. 같은 숫자는 싫어.py
  LeeMinjae/PGS-Coding_Test_Kit/StackQueue/12909. 올바른 괄호.py
  LeeMinjae/PGS-Coding_Test_Kit/StackQueue/42583. 다리를 지나는 트럭.py
  LeeMinjae/PGS-Coding_Test_Kit/StackQueue/42584. 주식가격.py
  LeeMinjae/PGS-Coding_Test_Kit/StackQueue/42586. 기능개발.py
  LeeMinjae/PGS-Coding_Test_Kit/StackQueue/42587. 프로세스.py
Labels: 🚚 rename

#40 [231102] Minseo-JO_1주차 문제 풀이
  Minseo-JO/백준/나무자르기.py
  Minseo-JO/프로그래머스/완주하지못한선수.py
  Minseo-JO/프로그래머스/전화번호 목록.py
  Minseo-JO/프로그래머스/폰켓몬.py
Labels: ✨ feat

#45 [231105] Imsyp_1주차 문제 풀이
  SangyeongPark/Algospot/Lv0/jumpGame.cpp
  SangyeongPark/Algospot/Lv1/Fence.cpp
  SangyeongPark/Programmers/Lv0/.vscode/settings.json
  SangyeongPark/Programmers/Lv0/arrflip2.cpp
  SangyeongPark/Programmers/Lv0/biggestNum.cpp
  SangyeongPark/Programmers/Lv0/day2_compofNums.cpp
  SangyeongPark/Programmers/Lv0/day2_divofTwo.cpp
  SangyeongPark/Programmers/Lv0/day2_doubleArr.cpp
  SangyeongPark/Programmers/Lv0/day2_sumofFrac.cpp
  SangyeongPark/Programmers/Lv0/day3_median.cpp
  SangyeongPark/Programmers/Lv0/day3_mode.cpp
  SangyeongPark/Programmers/Lv0/day3_noEven.cpp
  SangyeongPark/Programmers/Lv0/day3_remain.cpp
  SangyeongPark/Programmers/Lv0/day4_arrAver.cpp
  SangyeongPark/Programmers/Lv0/day4_pizzaDiv1.cpp
  SangyeongPark/Programmers/Lv0/day4_pizzaDiv2.cpp
  SangyeongPark/Programmers/Lv0/day4_pizzaDiv3.cpp
  SangyeongPark/Programmers/Lv0/day5_agePrint.cpp
  SangyeongPark/Programmers/Lv0/day5_arrFlip.cpp
  SangyeongPark/Programmers/Lv0/day5_clothesDiscount.cpp
  SangyeongPark/Programmers/Lv0/day5_iceAme.cpp
  SangyeongPark/Programmers/Lv0/day6_numofEvenOdd.cpp
  SangyeongPark/Programmers/Lv0/day6_printLoop.cpp
  SangyeongPark/Programmers/Lv0/day6_rightTri.cpp
  SangyeongPark/Programmers/Lv0/day6_stringFlip.cpp
Labels: ✨ feat

#47 [231107] intelsally_1,2주차 문제 풀이
  chaeyeonHan/Day 5. 수학, 배열.py
  chaeyeonHan/Day10_조건문, 배열, 수학, 시뮬레이션.py
  chaeyeonHan/Day11_수학,반복문.py
  chaeyeonHan/Day12_문자열,정렬,사칙연산,수학.py
  chaeyeonHan/Day13_문자열,배열,사칙연산,수학,조건문.py
  chaeyeonHan/Day14.py
  chaeyeonHan/Day15.py
  chaeyeonHan/Day1_사칙연산.py
  chaeyeonHan/Day2_사칙연산, 조건문,배열.py
  chaeyeonHan/Day3_사칙연산, 배열, 수학.py
  chaeyeonHan/Day4_수학, 배열.py
  chaeyeonHan/Day5_수학, 배열.py
  chaeyeonHan/Day6_문자열, 반복문, 출력, 배열, 조건문.py
  chaeyeonHan/Day7_문자열, 조건문, 수학, 반복문.py
  chaeyeonHan/Day8_배열, 구현 , 수학.py
  chaeyeonHan/Day9_수학, 문자열, 해시, 완전탐색, 조건문.py
  chaeyeonHan/PGS64061_크레인 인형뽑기 게임.py
Labels: ✨ feat

#49 [231107] LimSoYeong_2주차 문제 풀이
  LimSoYeong/PGS/12906 같은 숫자는 싫어 Level1.ipynb
  LimSoYeong/PGS/12909 올바른 괄호 Level2.ipynb
  LimSoYeong/PGS/181904 세로 읽기 Level0.py
  LimSoYeong/PGS/42586 기능개발 Level2.ipynb
  LimSoYeong/PGS/42747 H-Index Level2.ipynb
  LimSoYeong/PGS/64061 크레인 인형뽑기 게임 Level1.ipynb
Labels: ✨ feat

#52 [231107] JOONHYuk_LEE_2주차 문제 풀이
  JOONHYUk_LEE/[10일차]_문자열.py
  JOONHYUk_LEE/[120812]_최빈값 구하기.py
  JOONHYUk_LEE/[181913]_문자열 여러번 뒤집기.py
  JOONHYUk_LEE/[9일차]_문자열, 배열.py
Labels: ✨ feat

#54 [231107] mini-min_2주차 문제 풀이
  LeeMinjae/PGS-Coding_Test_Kit/StackQueue/64061. 크레인 인형뽑기 게임.py
  README.md
Labels: ✨ feat

#56 [231107] 한주상_2주차 문제풀이 추가
  한주상/2weeks.cpp
Labels: ✨ feat

#58 [231107] Imsyp_2주차 문제 풀이
  SangyeongPark/Programmers/Lv0/day10_q1.cpp
  SangyeongPark/Programmers/Lv0/day10_q2.cpp
  SangyeongPark/Programmers/Lv0/day10_q3.cpp
  SangyeongPark/Programmers/Lv0/day10_q4.cpp
  SangyeongPark/Programmers/Lv0/day7_angle.cpp
  SangyeongPark/Programmers/Lv0/day7_evenSum.cpp
  SangyeongPark/Programmers/Lv0/day7_lambggo.cpp
  SangyeongPark/Programmers/Lv0/day7_speMesDel.cpp
  SangyeongPark/Programmers/Lv0/day8_q1.cpp
  SangyeongPark/Programmers/Lv0/day8_q2.cpp
  SangyeongPark/Programmers/Lv0/day8_q3.cpp
  SangyeongPark/Programmers/Lv0/day8_q4.cpp
  SangyeongPark/Programmers/Lv0/day9_q1.cpp
  SangyeongPark/Programmers/Lv0/day9_q2.cpp
  SangyeongPark/Programmers/Lv0/day9_q3.cpp
  SangyeongPark/Programmers/Lv0/day9_q4.cpp
  SangyeongPark/Programmers/Lv1/crainDoll.cpp
  SangyeongPark/Programmers/Lv2/rightBracket.cpp
Labels: ✨ feat

#62 [231111] JOONHYuk_LEE_3주차 문제 풀이
  JOONHYUk_LEE/[11일차]_리스트(배열).py
  JOONHYUk_LEE/[12일차]_리스트(배열).py
  JOONHYUk_LEE/[13일차]_리스트(배열).py
  JOONHYUk_LEE/[14일차]_리스트(배열).py
Labels: ✨ feat

#68 [20231121] H-Software224_4주차 문제 풀이
  한주상/4weeks.cpp
Labels: ✨ feat
